// Mocks generated by Mockito 5.4.6 from annotations
// in test_giphy_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_giphy_app/domain/interactors/gif_interactor.dart' as _i5;
import 'package:test_giphy_app/domain/models/gif.dart' as _i2;
import 'package:test_giphy_app/domain/repositories/gif_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGif_0 extends _i1.SmartFake implements _i2.Gif {
  _FakeGif_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GifRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGifRepository extends _i1.Mock implements _i3.GifRepository {
  MockGifRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Gif>> getTrendingGifs({
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingGifs, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i4.Future<List<_i2.Gif>>.value(<_i2.Gif>[]),
          )
          as _i4.Future<List<_i2.Gif>>);

  @override
  _i4.Future<List<_i2.Gif>> searchGifs({
    required String? searchQuery,
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchGifs, [], {
              #searchQuery: searchQuery,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i4.Future<List<_i2.Gif>>.value(<_i2.Gif>[]),
          )
          as _i4.Future<List<_i2.Gif>>);

  @override
  _i4.Future<_i2.Gif> getGifDetails(String? gifId) =>
      (super.noSuchMethod(
            Invocation.method(#getGifDetails, [gifId]),
            returnValue: _i4.Future<_i2.Gif>.value(
              _FakeGif_0(this, Invocation.method(#getGifDetails, [gifId])),
            ),
          )
          as _i4.Future<_i2.Gif>);
}

/// A class which mocks [GifInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockGifInteractor extends _i1.Mock implements _i5.GifInteractor {
  MockGifInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Gif>> getGifList({
    required int? page,
    required int? pageSize,
    String? searchQuery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGifList, [], {
              #page: page,
              #pageSize: pageSize,
              #searchQuery: searchQuery,
            }),
            returnValue: _i4.Future<List<_i2.Gif>>.value(<_i2.Gif>[]),
          )
          as _i4.Future<List<_i2.Gif>>);

  @override
  _i4.Future<_i2.Gif> getGifDetails(String? gifId) =>
      (super.noSuchMethod(
            Invocation.method(#getGifDetails, [gifId]),
            returnValue: _i4.Future<_i2.Gif>.value(
              _FakeGif_0(this, Invocation.method(#getGifDetails, [gifId])),
            ),
          )
          as _i4.Future<_i2.Gif>);
}
