arb-dir: lib/presentation/res/localization
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/presentation/res/localization
nullable-getter: false
untranslated-messages-file: lib/presentation/res/localization/untranslated_messages.txt
